name: Polaris-Signature-Scan

on:
  push:
    branches:
      - bootstrapCI-CI
  pull_request:
    branches:
      - bootstrapCI-CI

jobs:
  polaris_signature_scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Run Polaris Signature Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: bootstrapCI
          polaris_assessment_types: "SCA,SAST"
          polaris_test_sca_type: "SCA-SIGNATURE,SCA-PACKAGE"
          include_diagnostics: true
